// Pacotes de categorias prontos para importação em lote.
// Cada categoria: { nome, tipo: "receita" | "despesa", cor, limite?,
//                   subcategorias?: ["Nome", ...] } — a importação converte
// cada nome em { id, nome } (formato do app).

export const PACOTES = [
  {
    id: "completo",
    nome: "Completo (recomendado)",
    descricao: "Estrutura completa pra finanças pessoais: 6 receitas + 21 despesas, já com subcategorias prontas. Importe tudo ou só o que faltar (nomes repetidos são pulados).",
    icone: "🗂️",
    categorias: [
      // ── RECEITAS ──────────────────────────────────────────────
      { nome: "Salário",              tipo: "receita", cor: "#3FB57F", subcategorias: ["13º salário", "Férias", "Bônus / PLR"] },
      { nome: "Renda Extra",          tipo: "receita", cor: "#69C895", subcategorias: ["Freelance", "Vendas", "Comissões"] },
      { nome: "Investimentos",        tipo: "receita", cor: "#8FCBA8", subcategorias: ["Dividendos", "Juros / Renda Fixa", "Aluguel recebido"] },
      { nome: "Benefícios",           tipo: "receita", cor: "#A8D9B8", subcategorias: ["Vale-refeição", "Vale-alimentação", "Auxílios"] },
      { nome: "Reembolsos",           tipo: "receita", cor: "#98C9A3" },
      { nome: "Outras Receitas",      tipo: "receita", cor: "#B5D6B2" },
      // ── DESPESAS · casa ───────────────────────────────────────
      { nome: "Moradia",              tipo: "despesa", cor: "#C9A574", subcategorias: ["Aluguel / Financiamento", "Condomínio", "IPTU", "Manutenção / Reforma", "Móveis / Decoração"] },
      { nome: "Contas de Casa",       tipo: "despesa", cor: "#E8B04B", subcategorias: ["Luz", "Água", "Gás", "Internet", "Celular"] },
      // ── alimentação ───────────────────────────────────────────
      { nome: "Mercado",              tipo: "despesa", cor: "#E07A5F", subcategorias: ["Feira", "Padaria", "Açougue", "Limpeza / Higiene"] },
      { nome: "Restaurantes & Delivery", tipo: "despesa", cor: "#D86F55", subcategorias: ["Restaurante", "Delivery / iFood", "Lanches / Café"] },
      // ── transporte ────────────────────────────────────────────
      { nome: "Transporte",           tipo: "despesa", cor: "#7AA0C4", subcategorias: ["Combustível", "Uber / Táxi", "Estacionamento", "Pedágio", "Transporte público"] },
      { nome: "Carro",                tipo: "despesa", cor: "#6F94B8", subcategorias: ["Manutenção", "IPVA / Licenciamento", "Seguro", "Lavagem"] },
      // ── saúde & pessoas ───────────────────────────────────────
      { nome: "Saúde",                tipo: "despesa", cor: "#D96D7A", subcategorias: ["Plano de saúde", "Farmácia", "Consultas / Exames", "Dentista", "Terapia"] },
      { nome: "Academia & Esporte",   tipo: "despesa", cor: "#C95F6E", subcategorias: ["Mensalidade", "Suplementos", "Equipamentos"] },
      { nome: "Educação",             tipo: "despesa", cor: "#A07ED1", subcategorias: ["Faculdade / Escola", "Cursos", "Livros", "Material"] },
      { nome: "Filhos",               tipo: "despesa", cor: "#9D8AC4", subcategorias: ["Escola", "Mesada", "Roupas", "Brinquedos", "Atividades"] },
      { nome: "Pets",                 tipo: "despesa", cor: "#A98BC0", subcategorias: ["Ração", "Veterinário", "Banho & Tosa"] },
      // ── estilo de vida ────────────────────────────────────────
      { nome: "Lazer & Viagens",      tipo: "despesa", cor: "#F2B65A", subcategorias: ["Cinema / Shows", "Viagens", "Hobbies", "Festas"] },
      { nome: "Vestuário & Beleza",   tipo: "despesa", cor: "#C79BD6", subcategorias: ["Roupas / Calçados", "Cabelo / Barba", "Cosméticos"] },
      { nome: "Assinaturas & Apps",   tipo: "despesa", cor: "#6FA8C9", subcategorias: ["Streaming", "Música", "Apps / IA", "Software"] },
      { nome: "Presentes & Doações",  tipo: "despesa", cor: "#9AA0A6", subcategorias: ["Presentes", "Doações / Dízimo"] },
      // ── financeiro ────────────────────────────────────────────
      { nome: "Impostos & Tarifas",   tipo: "despesa", cor: "#B85C4E", subcategorias: ["Imposto de Renda", "Tarifas bancárias", "Anuidade de cartão", "Multas"] },
      { nome: "Seguros",              tipo: "despesa", cor: "#8E7AB5", subcategorias: ["Vida", "Residencial"] },
      { nome: "Dívidas & Empréstimos", tipo: "despesa", cor: "#A88B5F", subcategorias: ["Parcelas", "Juros / Encargos"] },
      { nome: "Investimentos & Reserva", tipo: "despesa", cor: "#7FA58C", subcategorias: ["Aportes", "Reserva de emergência"] },
      { nome: "Imprevistos",          tipo: "despesa", cor: "#777E85" },
      { nome: "Outros",               tipo: "despesa", cor: "#8A8A93" },
    ],
  },
  {
    id: "pf-essencial",
    nome: "Pessoa Física Essencial",
    descricao: "Cobertura básica para finanças pessoais do dia a dia.",
    icone: "👤",
    categorias: [
      { nome: "Salário",            tipo: "receita", cor: "#3FB57F" },
      { nome: "Outras Receitas",    tipo: "receita", cor: "#69C895" },
      { nome: "Moradia",            tipo: "despesa", cor: "#C9A574" },
      { nome: "Alimentação",        tipo: "despesa", cor: "#E07A5F" },
      { nome: "Transporte",         tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Saúde",              tipo: "despesa", cor: "#D96D7A" },
      { nome: "Educação",           tipo: "despesa", cor: "#A07ED1" },
      { nome: "Lazer",              tipo: "despesa", cor: "#F2B65A" },
      { nome: "Vestuário",          tipo: "despesa", cor: "#B58FCE" },
      { nome: "Assinaturas",        tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Cartão de Crédito",  tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Imprevistos",        tipo: "despesa", cor: "#9AA0A6" },
    ],
  },
  {
    id: "loja-af4",
    nome: "Loja de Veículos AF4",
    descricao: "Plano contábil enxuto para revenda de veículos.",
    icone: "🚗",
    categorias: [
      { nome: "Venda de Veículo",       tipo: "receita", cor: "#3FB57F" },
      { nome: "Comissão de Venda",      tipo: "receita", cor: "#69C895" },
      { nome: "Repasse / Troca",        tipo: "receita", cor: "#8FCBA8" },
      { nome: "Serviços (Vistoria etc)",tipo: "receita", cor: "#A8D9B8" },
      { nome: "Compra de Veículo",      tipo: "despesa", cor: "#E07A5F" },
      { nome: "Despachante / DETRAN",   tipo: "despesa", cor: "#C9A574" },
      { nome: "Manutenção / Mecânica",  tipo: "despesa", cor: "#D96D7A" },
      { nome: "Estética / Lavagem",     tipo: "despesa", cor: "#F2B65A" },
      { nome: "Combustível",            tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Aluguel do Pátio",       tipo: "despesa", cor: "#C9A574" },
      { nome: "Energia / Água",         tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Internet / Telefone",    tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Marketing / Anúncios",   tipo: "despesa", cor: "#B58FCE" },
      { nome: "Salários / Pró-labore",  tipo: "despesa", cor: "#A07ED1" },
      { nome: "Comissões Pagas",        tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Impostos / Taxas",       tipo: "despesa", cor: "#D96D7A" },
      { nome: "Contador",               tipo: "despesa", cor: "#9AA0A6" },
      { nome: "Imprevistos",            tipo: "despesa", cor: "#777E85" },
    ],
  },
  {
    id: "autonomo",
    nome: "Autônomo / Freelance",
    descricao: "Para profissionais liberais e prestadores de serviço.",
    icone: "💼",
    categorias: [
      { nome: "Honorários / Serviços",  tipo: "receita", cor: "#3FB57F" },
      { nome: "Bonificação / Extra",    tipo: "receita", cor: "#69C895" },
      { nome: "Royalties / Direitos",   tipo: "receita", cor: "#8FCBA8" },
      { nome: "Moradia / Home Office",  tipo: "despesa", cor: "#C9A574" },
      { nome: "Alimentação",            tipo: "despesa", cor: "#E07A5F" },
      { nome: "Transporte",             tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Saúde / Plano",          tipo: "despesa", cor: "#D96D7A" },
      { nome: "Cursos / Educação",      tipo: "despesa", cor: "#A07ED1" },
      { nome: "Software / Ferramentas", tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Marketing Pessoal",      tipo: "despesa", cor: "#B58FCE" },
      { nome: "Coworking / Escritório", tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Impostos (INSS, IRPF)",  tipo: "despesa", cor: "#D96D7A" },
      { nome: "Contador",               tipo: "despesa", cor: "#9AA0A6" },
      { nome: "Reserva de Emergência",  tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Imprevistos",            tipo: "despesa", cor: "#777E85" },
    ],
  },
  {
    id: "familia",
    nome: "Família Completa",
    descricao: "Plano detalhado para orçamento familiar.",
    icone: "🏠",
    categorias: [
      { nome: "Salário Titular",        tipo: "receita", cor: "#3FB57F" },
      { nome: "Salário Cônjuge",        tipo: "receita", cor: "#69C895" },
      { nome: "Outras Receitas",        tipo: "receita", cor: "#8FCBA8" },
      { nome: "Aluguel / Financiamento",tipo: "despesa", cor: "#C9A574" },
      { nome: "Condomínio",             tipo: "despesa", cor: "#B89766" },
      { nome: "IPTU",                   tipo: "despesa", cor: "#A88B5F" },
      { nome: "Energia",                tipo: "despesa", cor: "#F2B65A" },
      { nome: "Água",                   tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Gás",                    tipo: "despesa", cor: "#E89C49" },
      { nome: "Internet / TV",          tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Mercado",                tipo: "despesa", cor: "#E07A5F" },
      { nome: "Restaurantes",           tipo: "despesa", cor: "#D86F55" },
      { nome: "Transporte / Combustível", tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Escola dos Filhos",      tipo: "despesa", cor: "#A07ED1" },
      { nome: "Plano de Saúde",         tipo: "despesa", cor: "#D96D7A" },
      { nome: "Medicamentos",           tipo: "despesa", cor: "#C95F6E" },
      { nome: "Vestuário",              tipo: "despesa", cor: "#B58FCE" },
      { nome: "Lazer / Viagens",        tipo: "despesa", cor: "#F2B65A" },
      { nome: "Assinaturas",            tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Pets",                   tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Doações",                tipo: "despesa", cor: "#9AA0A6" },
      { nome: "Imprevistos",            tipo: "despesa", cor: "#777E85" },
    ],
  },
  {
    id: "ecommerce",
    nome: "E-commerce",
    descricao: "Para loja virtual / dropshipping / produtos digitais.",
    icone: "🛒",
    categorias: [
      { nome: "Vendas Online",          tipo: "receita", cor: "#3FB57F" },
      { nome: "Marketplace",            tipo: "receita", cor: "#69C895" },
      { nome: "Assinaturas / Recorrência", tipo: "receita", cor: "#8FCBA8" },
      { nome: "Fornecedores / Estoque", tipo: "despesa", cor: "#E07A5F" },
      { nome: "Frete / Logística",      tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Embalagem",              tipo: "despesa", cor: "#C9A574" },
      { nome: "Taxas Marketplace",      tipo: "despesa", cor: "#D96D7A" },
      { nome: "Gateway / Pix",          tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Anúncios (Meta/Google)", tipo: "despesa", cor: "#B58FCE" },
      { nome: "Hospedagem / Software",  tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Designer / Conteúdo",    tipo: "despesa", cor: "#A07ED1" },
      { nome: "Salários / Pró-labore",  tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Impostos / Simples",     tipo: "despesa", cor: "#D96D7A" },
      { nome: "Contador",               tipo: "despesa", cor: "#9AA0A6" },
    ],
  },
  {
    id: "investidor",
    nome: "Investidor Ativo",
    descricao: "Para quem opera ativos e quer rastrear o fluxo do portfólio.",
    icone: "📈",
    categorias: [
      { nome: "Dividendos / Proventos", tipo: "receita", cor: "#3FB57F" },
      { nome: "Aluguéis Recebidos",     tipo: "receita", cor: "#69C895" },
      { nome: "Juros / Renda Fixa",     tipo: "receita", cor: "#8FCBA8" },
      { nome: "Ganho de Capital",       tipo: "receita", cor: "#A8D9B8" },
      { nome: "Aporte / Compra Ativo",  tipo: "despesa", cor: "#C9A574" },
      { nome: "Corretagem / Taxas",     tipo: "despesa", cor: "#D96D7A" },
      { nome: "Imposto sobre Operações", tipo: "despesa", cor: "#E07A5F" },
      { nome: "Custódia",               tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Assinaturas / Research", tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Educação Financeira",    tipo: "despesa", cor: "#A07ED1" },
    ],
  },
];

export function getPacote(id) {
  return PACOTES.find(p => p.id === id) || null;
}
