// Pacotes de categorias prontos para importação em lote.
// Cada categoria: { nome, tipo: "receita" | "despesa", cor, limite? }

export const PACOTES = [
  {
    id: "pf-essencial",
    nome: "Pessoa Física Essencial",
    descricao: "Cobertura básica para finanças pessoais do dia a dia.",
    icone: "👤",
    categorias: [
      { nome: "Salário",            tipo: "receita", cor: "#3FB57F" },
      { nome: "Outras Receitas",    tipo: "receita", cor: "#69C895" },
      { nome: "Moradia",            tipo: "despesa", cor: "#C9A574" },
      { nome: "Alimentação",        tipo: "despesa", cor: "#E07A5F" },
      { nome: "Transporte",         tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Saúde",              tipo: "despesa", cor: "#D96D7A" },
      { nome: "Educação",           tipo: "despesa", cor: "#A07ED1" },
      { nome: "Lazer",              tipo: "despesa", cor: "#F2B65A" },
      { nome: "Vestuário",          tipo: "despesa", cor: "#B58FCE" },
      { nome: "Assinaturas",        tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Cartão de Crédito",  tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Imprevistos",        tipo: "despesa", cor: "#9AA0A6" },
    ],
  },
  {
    id: "loja-af4",
    nome: "Loja de Veículos AF4",
    descricao: "Plano contábil enxuto para revenda de veículos.",
    icone: "🚗",
    categorias: [
      { nome: "Venda de Veículo",       tipo: "receita", cor: "#3FB57F" },
      { nome: "Comissão de Venda",      tipo: "receita", cor: "#69C895" },
      { nome: "Repasse / Troca",        tipo: "receita", cor: "#8FCBA8" },
      { nome: "Serviços (Vistoria etc)",tipo: "receita", cor: "#A8D9B8" },
      { nome: "Compra de Veículo",      tipo: "despesa", cor: "#E07A5F" },
      { nome: "Despachante / DETRAN",   tipo: "despesa", cor: "#C9A574" },
      { nome: "Manutenção / Mecânica",  tipo: "despesa", cor: "#D96D7A" },
      { nome: "Estética / Lavagem",     tipo: "despesa", cor: "#F2B65A" },
      { nome: "Combustível",            tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Aluguel do Pátio",       tipo: "despesa", cor: "#C9A574" },
      { nome: "Energia / Água",         tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Internet / Telefone",    tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Marketing / Anúncios",   tipo: "despesa", cor: "#B58FCE" },
      { nome: "Salários / Pró-labore",  tipo: "despesa", cor: "#A07ED1" },
      { nome: "Comissões Pagas",        tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Impostos / Taxas",       tipo: "despesa", cor: "#D96D7A" },
      { nome: "Contador",               tipo: "despesa", cor: "#9AA0A6" },
      { nome: "Imprevistos",            tipo: "despesa", cor: "#777E85" },
    ],
  },
  {
    id: "autonomo",
    nome: "Autônomo / Freelance",
    descricao: "Para profissionais liberais e prestadores de serviço.",
    icone: "💼",
    categorias: [
      { nome: "Honorários / Serviços",  tipo: "receita", cor: "#3FB57F" },
      { nome: "Bonificação / Extra",    tipo: "receita", cor: "#69C895" },
      { nome: "Royalties / Direitos",   tipo: "receita", cor: "#8FCBA8" },
      { nome: "Moradia / Home Office",  tipo: "despesa", cor: "#C9A574" },
      { nome: "Alimentação",            tipo: "despesa", cor: "#E07A5F" },
      { nome: "Transporte",             tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Saúde / Plano",          tipo: "despesa", cor: "#D96D7A" },
      { nome: "Cursos / Educação",      tipo: "despesa", cor: "#A07ED1" },
      { nome: "Software / Ferramentas", tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Marketing Pessoal",      tipo: "despesa", cor: "#B58FCE" },
      { nome: "Coworking / Escritório", tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Impostos (INSS, IRPF)",  tipo: "despesa", cor: "#D96D7A" },
      { nome: "Contador",               tipo: "despesa", cor: "#9AA0A6" },
      { nome: "Reserva de Emergência",  tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Imprevistos",            tipo: "despesa", cor: "#777E85" },
    ],
  },
  {
    id: "familia",
    nome: "Família Completa",
    descricao: "Plano detalhado para orçamento familiar.",
    icone: "🏠",
    categorias: [
      { nome: "Salário Titular",        tipo: "receita", cor: "#3FB57F" },
      { nome: "Salário Cônjuge",        tipo: "receita", cor: "#69C895" },
      { nome: "Outras Receitas",        tipo: "receita", cor: "#8FCBA8" },
      { nome: "Aluguel / Financiamento",tipo: "despesa", cor: "#C9A574" },
      { nome: "Condomínio",             tipo: "despesa", cor: "#B89766" },
      { nome: "IPTU",                   tipo: "despesa", cor: "#A88B5F" },
      { nome: "Energia",                tipo: "despesa", cor: "#F2B65A" },
      { nome: "Água",                   tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Gás",                    tipo: "despesa", cor: "#E89C49" },
      { nome: "Internet / TV",          tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Mercado",                tipo: "despesa", cor: "#E07A5F" },
      { nome: "Restaurantes",           tipo: "despesa", cor: "#D86F55" },
      { nome: "Transporte / Combustível", tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Escola dos Filhos",      tipo: "despesa", cor: "#A07ED1" },
      { nome: "Plano de Saúde",         tipo: "despesa", cor: "#D96D7A" },
      { nome: "Medicamentos",           tipo: "despesa", cor: "#C95F6E" },
      { nome: "Vestuário",              tipo: "despesa", cor: "#B58FCE" },
      { nome: "Lazer / Viagens",        tipo: "despesa", cor: "#F2B65A" },
      { nome: "Assinaturas",            tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Pets",                   tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Doações",                tipo: "despesa", cor: "#9AA0A6" },
      { nome: "Imprevistos",            tipo: "despesa", cor: "#777E85" },
    ],
  },
  {
    id: "ecommerce",
    nome: "E-commerce",
    descricao: "Para loja virtual / dropshipping / produtos digitais.",
    icone: "🛒",
    categorias: [
      { nome: "Vendas Online",          tipo: "receita", cor: "#3FB57F" },
      { nome: "Marketplace",            tipo: "receita", cor: "#69C895" },
      { nome: "Assinaturas / Recorrência", tipo: "receita", cor: "#8FCBA8" },
      { nome: "Fornecedores / Estoque", tipo: "despesa", cor: "#E07A5F" },
      { nome: "Frete / Logística",      tipo: "despesa", cor: "#7AA0C4" },
      { nome: "Embalagem",              tipo: "despesa", cor: "#C9A574" },
      { nome: "Taxas Marketplace",      tipo: "despesa", cor: "#D96D7A" },
      { nome: "Gateway / Pix",          tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Anúncios (Meta/Google)", tipo: "despesa", cor: "#B58FCE" },
      { nome: "Hospedagem / Software",  tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Designer / Conteúdo",    tipo: "despesa", cor: "#A07ED1" },
      { nome: "Salários / Pró-labore",  tipo: "despesa", cor: "#9D8AC4" },
      { nome: "Impostos / Simples",     tipo: "despesa", cor: "#D96D7A" },
      { nome: "Contador",               tipo: "despesa", cor: "#9AA0A6" },
    ],
  },
  {
    id: "investidor",
    nome: "Investidor Ativo",
    descricao: "Para quem opera ativos e quer rastrear o fluxo do portfólio.",
    icone: "📈",
    categorias: [
      { nome: "Dividendos / Proventos", tipo: "receita", cor: "#3FB57F" },
      { nome: "Aluguéis Recebidos",     tipo: "receita", cor: "#69C895" },
      { nome: "Juros / Renda Fixa",     tipo: "receita", cor: "#8FCBA8" },
      { nome: "Ganho de Capital",       tipo: "receita", cor: "#A8D9B8" },
      { nome: "Aporte / Compra Ativo",  tipo: "despesa", cor: "#C9A574" },
      { nome: "Corretagem / Taxas",     tipo: "despesa", cor: "#D96D7A" },
      { nome: "Imposto sobre Operações", tipo: "despesa", cor: "#E07A5F" },
      { nome: "Custódia",               tipo: "despesa", cor: "#8E7AB5" },
      { nome: "Assinaturas / Research", tipo: "despesa", cor: "#6FA8C9" },
      { nome: "Educação Financeira",    tipo: "despesa", cor: "#A07ED1" },
    ],
  },
];

export function getPacote(id) {
  return PACOTES.find(p => p.id === id) || null;
}
